### PR TITLE
Do not reset HNO3, NH3, and HCL back, after calling gas-aerosol exchange

### PR DESCRIPTION
**Pull request by mingxuanwupnnl**
Add gas species to the list (HNO3, NH3, HCL), so that they won't be reset back to the values before calling aero_model_gasaerexch. This change is BFB for F20TR_chemUCI-Linozv3 compset (I have done a test using my branch, see /lcrc/group/e3sm/ac.mwu/archive/20220701.v2.LR.bi-grid.amip.chemUCI-Linozv3.chrysalis/run ). However, it corrects the unrealistic high nitrate burdens (~200 Tg for global mean) for the coupled chemUCI and MOSAIC.

Future attention should be paid to this piece of code, for example SOA development which has multiple SOAG species.

Also removed a .swp file, which seems to be some cache.

### CODE REVIEW

**Review by tangq — CHANGES_REQUESTED** [review]
The file components/eam/src/chemistry/mozart/.mo_gas_phase_chemdr.F90.swp should be deleted from the PR.

**Comment by tangq** [comment]
A bit more information about this PR:
The purpose of the reset call after aero_model_gasaerexch is to remove inconsistent changes to the gas tracers outside of chemistry solvers. However, some tracer changes should be kept, including DMS, SO2, H2SO4, SOAG, and the newly added ones from this PR (HNO3, NH3, and HCL).

**Comment by mingxuanwupnnl** [comment]
@tangq the .swp file was already in NGD_v3atm. I'm trying to delete it for this PR not adding one. Are you suggesting we should use another PR to delete it or we should not delete it?

**Comment by tangq** [comment]
@mingxuanwupnnl , ah, I see. It is weird that we have the .swp file in the existing code. I don't think we need a separate PR for deleting the file. The PR looks good. I am merging it now.

**Pull request merged**
