### PR TITLE
Improve wet removal and add low Nc limit 

### PR DESCRIPTION
**Pull request by yunpengshan2014**
Aerosol wet removal improvement: 
1. Use vertical velocity from ZMmp scheme in the deep convection wet removal
2. Detrain the cloud-borne aerosol into stratiform
3. Reorder the stratiform wet removal and the deep convection wet removal
4. Add Nc limit (default 10 per CC) in the P3 scheme
5. Fix the hard-coded qc exponent in the enhancement factors of auto-conversion and accretion

### CODE REVIEW

**Comment by crterai** [comment]
A series of custom-10, custom-30 tests all came back BFB. 
```
6e6451f2bd7e8865cba6b303a7ccb3a5  atm_custom-10_1x2_nmonths.txt
6e6451f2bd7e8865cba6b303a7ccb3a5  atm_custom-10_2x1_nmonths.txt
6e6451f2bd7e8865cba6b303a7ccb3a5  atm_custom-30_1x2_nmonths.txt
```

**Review by crterai — APPROVED** [review]
Thanks to Xiaoliang Song for looking through the code and giving the green light on the changes associated with the ZM scheme.

**Comment by crterai** [comment]
@wlin7 - if it looks okay, this PR is ready to be merged to the NGD_v3atm branch.

**Comment by wlin7** [comment]
Merged to NGD_v3atm. Testing underway. DIFFs in nml and results are expected.

**Comment by wlin7** [comment]
Alert:[ Compy ERS tests](https://compy-dtn.pnl.gov/linw288/v3atm/testings/20230118.post.PR-34.compy.txt) on ne30pg2 failed, though ne4pg2 passed. (See the line of Compare_base_rest). 227 out of 448 fields in cpl.hi have non-zero differences.

**Pull request merged**
