### PR TITLE
Yfenganl/atm/chem uci chem mzt mosaic dustemis k14 amip

### PR DESCRIPTION
**Pull request by yfenganl**
Implement the new dust emission scheme
  
github branch: yfenganl/atm/chemUCI-chemMZT-MOSAIC-dustemisK14_AMIP

rebased to the branch: mingxuanwupnnl/atm/chemUCI-chemMZT-MOSAIC_AMIP

Files modified:

1. do not update soil erodibility factor:
components/eam/src/chemistry/modal_aero/dust_model.F90

2. modify the dust emissions:
components/elm/src/biogeochem/DUSTMod.F90

3. retune emission factor:
components/eam/bld/namelist_files/namelist_defaults_eam.xml

[non-BFB]

### CODE REVIEW

**Review by mingxuanwupnnl — CHANGES_REQUESTED** [review]
@yfenganl The dust emission scheme looks good to me. What dust optical depth does the current dust_emis_fact tune for?

It seems to be merge conflicts for mo_gas_phase_chemdr.F90. I would suggest rebasing to the current NGD_v3atm branch. Or resolve the conflicts by keeping mo_gas_phase_chemdr.F90 in NGD_v3atm branch?

@wlin7 what would would you suggest?

**Comment by yfenganl** [comment]
> @mingxuanwupnnl yes, I could replace the file mo_gas_phase_chemdr.F90 with the one from NGD_v3atm branch to resolve the conflict. Will get to that tomorrow. Thanks for the feedback.

**Comment by yfenganl** [comment]
@mingxuanwupnnl @hwangacme : I have resolved the small conflict in mo_gas_phase_chemdr.F90 by deleting the extra space on Line 1330. it seems no conflicts with the base branch NGD_v3atm now.

**Review by hwangacme — APPROVED** [review]

**Review by mingxuanwupnnl — APPROVED** [review]
@yfenganl @hwangacme we might consider add a switch flag in the future, so we can change  back to Z01 dust emission scheme, although K14 probably performs better than Z01 in may aspects.

**Comment by wlin7** [comment]
Just a final check, @yfenganl , @hwangacme , @mingxuanwupnnl . Can this PR be merged as is now? Based on the changes, the new default configuration will lead to NBFB results, correct? I am adding non-BFB label to this PR for quick future reference.

**Comment by mingxuanwupnnl** [comment]
@wlin7 I think if there is no surprise for test results (probably not), it is good to be merged.

@yfenganl could you confirm and update your test results (SMS, ERS, etc) on confluence? Thank you.

**Comment by wlin7** [comment]
Merged to NGD_v3atm. CIME tests are underway.

**Pull request merged**
