### PR TITLE
Fix chemUCI high NOx

### PR DESCRIPTION
**Pull request by tangq**
This PR corrects the surface emissions for chemUCI and fixes the high NOx issue. The NO surface emissions could be added in upper troposphere and lower stratosphere. With this fix, it will be limited to the bottom layers.

The test has be done successfully and documented at this [page](https://acme-climate.atlassian.net/wiki/spaces/NGDAP/pages/3520593921/20220906.v2.LR.bi-grid.amip.chemUCI+Linozv3). The results show that the high NOx is gone.

[non-BFB]

### CODE REVIEW

**Review by mingxuanwupnnl — COMMENTED** [review]
@tangq, could you add some more details in the description for this bug and the fix? The revised method is to evenly distribute surface emissions to the three layers, right? The previous one is not clear to me. Not sure if it just add emissions in a layer or can add emissions in several layers in the stratosphere.

**Comment by tangq** [comment]
@mingxuanwupnnl , the buggy code adds NO into layers from bottom to top with a limit of 2x original till it runs out. The new code changes it to adding emissions uniformly into the bottom 3 layers.

**Review by mingxuanwupnnl — APPROVED** [review]
@tangq Just approve it for now. However, I think we still need more discussions/experiments to justify this change.

**Comment by tangq** [comment]
@mingxuanwupnnl , there is probably no perfect solution. When thinking more about it (especially from the point of chemistry-aerosol coupled tuning), we can make it a tunable parameter to have more control on the radical levels without modifying the overall diffusion. We can implement the parameter option later as a separate PR when needed.

**Comment by wlin7** [comment]
Merged.

**Pull request merged**
