### PR TITLE
A revised handling of cflx as a stealth feature

### PR DESCRIPTION
**Pull request by huiwanpnnl**
**This PR replaces PR #4**

This PR includes the same essential changes in the old PR, but
- The implementation is based off Wuyin's <NGD_atm> branch (which has updated test capabilities).
- Comments in the code have been improved to clarify which tracers are affected and which are not.
- Initialization of `cam_in%cflx` is revised to ensure BFB restart.

------

This PR adds an optional revision to the numerical process coupling at the `tphysbc`/`tphysac` level to couple the surface emissions of tracers more tightly with the turbulent transport. This is done by revising where in the time integration loop the surface fluxes in `cam_in%cflx(:,2:)` are applied to update the tracer mixing ratios.

The revision was motivated by the known issues of overly short dust lifetime in EAMv1 and the very strong sensitivity of the dust lifetime to vertical resolution, see [Feng et al., 2022](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021MS002909) for the v1 results.

The implementation of the revised coupling is described below in the "code modifications" section.

Impacts of the revised coupling was initially evaluated in v1. More recently, evaluation was done in v2 using a 5-year F2010 simulation and a 30-year AMIP (F20TR) simulation using the [huiwanpnnl/atm/aerosol_process_coupling branch in the E3SM repo](https://github.com/E3SM-Project/E3SM/tree/huiwanpnnl/atm/aerosol_process_coupling). Highlights of the results can be found on [this Confluence page](https://acme-climate.atlassian.net/wiki/spaces/NGDAP/pages/3469312014/Revised+aerosol+process+coupling+for+E3SMv3) and in [this slide deck](https://acme-climate.atlassian.net/wiki/spaces/NGDAP/pages/3469312014/Revised+aerosol+process+coupling+for+E3SMv3).

**Code modifications**

- The subroutine `clubb_surface` in `clubb_intr.F90` was split into two parts:
   - The calculations of `ustar` and the Obukhov length remain in `clubb_surface`.
   - The calculation of tracer mixing ratio tendencies using `cam_in%clfx` was moved to a new subroutine `cflx_tend` in a new module in `cflx.F90`
  
- A new namelist variable `cflx_cpl_opt` was added.
   - _`cflx_cpl_opt = 1` (default) gives the original coupling in v2._ 
   
   There, the subroutine `cflx_tend` is called immediately after `clubb_surface` followed by a `call physics_update(...)`. This gives the original process coupling in EAMv2 and the results are BFB.
   
   - _`cflx_cpl_opt = 2` activates the revised coupling._ 
   
   The call of `cflx_tend` and the corresponding `call physics_update(...)` are moved to right before the cloud macro-microphysics sub-cycles in `tphysbc`, so that the tracers emitted to the lowest model layer can be transported to upper layers by `CLUBB` or `dropmixnuc`.

    Note that `cflx_cpl_opt = 2` does __not__ affect water vapor. Neither does it affect tracers whose portion of `cam_in%cflx` is zero when `clubb_surface` is called.

- The initialization of `cam_in%cflx(:,2:)` with zeros was moved from the `atm_import` subroutine in `components/eam/src/cpl/atm_import_export.F90` to the `read_restart_physics` subroutine in `components/eam/src/physics/cam/restart_physics.F90` to avoid incorrectly zeroing out the values read in from a restart file. This ensures BFB restart for both the default model and for `cflx_cpl_opt = 2`.

### CODE REVIEW

**Review by wlin7 — APPROVED** [review]
The changes look good and the available developer and integration cime tests BFB with NGD_v3atm baselines.

**Comment by rljacob** [comment]
Are you starting development branches from the NGD_v3atm branch?  I didn't think that was in the workflow.

**Comment by wlin7** [comment]
> Are you starting development branches from the NGD_v3atm branch? I didn't think that was in the workflow.

@rljacob . I might not understand your comments correctly. Git log does show this branched started from the NGD_v3atm branch of Sept. 26.

**Comment by wlin7** [comment]
Merged to NGD_v3atm.

**Pull request merged**
