### PR TITLE
Add chemistry mechanism file for chemUCI-MAM5-VBS

### PR DESCRIPTION
**Pull request by mingxuanwupnnl**
Add the chemistry mechanism file for chemUCI-MAM5-VBS, which will be new default gas chemistry-aerosol configuration.

BFB for chemUCI only simulations

### CODE REVIEW

**Comment by mingxuanwupnnl** [comment]
> The file name (pp_chemUCI_linozv3_mam5_resus_mom_cnst_no3_oh_vbs_tag.in) is really long. Can it be shortened?

resus_mom is from previous naming convention: aerosol precipitation resuspension and marine organic aerosol, cnst_no3_oh is for MAM5 treatment using constant NO3 radical and OH in the stratosphere.

We can do  pp_chemUCI_linozv3_mam5_vbs_tag.in or pp_chemUCI_linozv3_mam5_resus_mom_vbs.in.
@keziming @hwangacme What do you think?

**Comment by hwangacme** [comment]
> 

Since resus_mom has been the default setting for v1 and v2, it can be removed from the name. cnst_no3_oh might be needed if this could be changed in future versions. "tag" can be dropped I think.

**Review by hwangacme — APPROVED** [review]

**Comment by mingxuanwupnnl** [comment]
@keziming do you think it is okay to remove cnst_no3_oh in the file name? 
Which one you think is better, pp_chemUCI_linozv3_mam5_vbs.in or pp_chemUCI_linozv3_mam5_cnst_no3_oh_vbs.in

**Comment by mingxuanwupnnl** [comment]
@tangq @hwangacme @keziming Thanks for the comments. I just renamed the file as well as the one with MOSAIC.

@wlin7 I think it is now good to be merged to NGD_v3atm branch.

**Comment by wlin7** [comment]
Merged to NGD_v3atm.

**Pull request merged**
